name: pawsbilities_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  image_picker: ^1.0.7
  font_awesome_flutter: ^10.5.0
  convex_bottom_bar: ^3.2.0
  flutter_svg: ^2.0.9
  flutter_card_swiper: ^7.0.2
  flip_card: ^0.7.0
  google_maps_flutter: ^2.6.1
  location: ^5.0.3
  google_place: ^0.4.7
  geolocator: ^12.0.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/logo.png
    - assets/images/Profile_pic.jpg
    - assets/images/matchscreen_design.png 
    - assets/images/dog.png
    - assets/images/dog2.jpg
    - assets/images/dog3.jpg
    - assets/images/dog4.jpg
    - assets/images/avatar.png
    - assets/images/location_enable.png
    - assets/images/notification_enable.png
    - assets/images/matches_done.png
    - assets/images/welcome_bg.png
    - assets/images/paw_txt.png
    - assets/icons/
    

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700


