// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAa3lisDe2gcZBKnve-GtEPB9osqdC99gI',
    appId: '1:1029869899195:web:8c7042b9a7143b8f18489e',
    messagingSenderId: '1029869899195',
    projectId: 'pawsibilities-7032c',
    authDomain: 'pawsibilities-7032c.firebaseapp.com',
    storageBucket: 'pawsibilities-7032c.firebasestorage.app',
    measurementId: 'G-L9XXSPCGZP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc3opRAJAuYC421IQkAO9zM44aYQKdks4',
    appId: '1:1029869899195:android:62566d54e7d3bfbf18489e',
    messagingSenderId: '1029869899195',
    projectId: 'pawsibilities-7032c',
    storageBucket: 'pawsibilities-7032c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwio5XIMXZY05ylDj2V8YPreqH17h3jf0',
    appId: '1:1029869899195:ios:baf9a50b99d9eb1718489e',
    messagingSenderId: '1029869899195',
    projectId: 'pawsibilities-7032c',
    storageBucket: 'pawsibilities-7032c.firebasestorage.app',
    iosBundleId: 'com.example.pawsbilitiesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwio5XIMXZY05ylDj2V8YPreqH17h3jf0',
    appId: '1:1029869899195:ios:baf9a50b99d9eb1718489e',
    messagingSenderId: '1029869899195',
    projectId: 'pawsibilities-7032c',
    storageBucket: 'pawsibilities-7032c.firebasestorage.app',
    iosBundleId: 'com.example.pawsbilitiesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAa3lisDe2gcZBKnve-GtEPB9osqdC99gI',
    appId: '1:1029869899195:web:1731e859c328e9ac18489e',
    messagingSenderId: '1029869899195',
    projectId: 'pawsibilities-7032c',
    authDomain: 'pawsibilities-7032c.firebaseapp.com',
    storageBucket: 'pawsibilities-7032c.firebasestorage.app',
    measurementId: 'G-6PYWQDZCC1',
  );
}
